version: '3'
services:
  chatbot:
    image: comp7940-lab1-chatbot:latest
    environment:
      - TELEGRAM_TOKEN=
      - REDIS_HOST=redis
      - REDIS_PWD=comp7940passwordlab8
      - REDIS_PORT=6379
      - REDIS_DECODE=True
      - REDIS_USERNAME=default
      - GPT_URL=https://genai.hkbu.edu.hk/general/rest
      - GPT_MODEL=gpt-4-o-mini
      - GPT_VERSION=2024-05-01-preview
      - GPT_TOKEN=
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:  ["/usr/local/etc/redis/redis.conf"]